"""add_role_validation_and_profile_fields

Revision ID: 07c8e48b10dd
Revises: aef8fa6c4f2f
Create Date: 2026-08-17 20:08:48.535620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07c8e48b10dd'
down_revision: Union[str, Sequence[str], None] = 'aef8fa6c4f2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM users")
    op.add_column('users', sa.Column('employee_id', sa.String(), nullable=False))
    op.add_column('users', sa.Column('department', sa.String(), nullable=True))
    op.add_column('users', sa.Column('designation', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.create_unique_constraint('users_employee_id_key', 'users', ['employee_id'])
    op.create_check_constraint(
        'check_valid_role',
        'users',
        sa.column('role').in_(['Employee', 'Reviewer', 'Manager', 'Administrator'])
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_valid_role', 'users', type_='check')
    op.drop_constraint('users_employee_id_key', 'users', type_='unique')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'designation')
    op.drop_column('users', 'department')
    op.drop_column('users', 'employee_id')
    # ### end Alembic commands ###

