"""create alternatives table

Revision ID: 1175256cbc30
Revises: cce93a22c01e
Create Date: 2026-08-21 21:32:44.761607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1175256cbc30'
down_revision: Union[str, Sequence[str], None] = 'cce93a22c01e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alternatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('pros', sa.Text(), nullable=False),
    sa.Column('cons', sa.Text(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('feasibility_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alternatives_decision_id'), 'alternatives', ['decision_id'], unique=False)
    op.create_index(op.f('ix_alternatives_id'), 'alternatives', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alternatives_id'), table_name='alternatives')
    op.drop_index(op.f('ix_alternatives_decision_id'), table_name='alternatives')
    op.drop_table('alternatives')
    # ### end Alembic commands ###
