"""add thread support to comments

Revision ID: 1dbf87fe74ba
Revises: c44c47939a24
Create Date: 2026-08-24 10:10:25.753259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dbf87fe74ba'
down_revision: Union[str, Sequence[str], None] = 'c44c47939a24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('thread_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'discussion_threads', ['thread_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'thread_id')
    # ### end Alembic commands ###
