"""create discussion threads table

Revision ID: 29ee328865c1
Revises: 0dbdef96df72
Create Date: 2026-08-21 16:23:55.441295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29ee328865c1'
down_revision: Union[str, Sequence[str], None] = '0dbdef96df72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discussion_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discussion_threads_created_by'), 'discussion_threads', ['created_by'], unique=False)
    op.create_index(op.f('ix_discussion_threads_decision_id'), 'discussion_threads', ['decision_id'], unique=False)
    op.create_index(op.f('ix_discussion_threads_id'), 'discussion_threads', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discussion_threads_id'), table_name='discussion_threads')
    op.drop_index(op.f('ix_discussion_threads_decision_id'), table_name='discussion_threads')
    op.drop_index(op.f('ix_discussion_threads_created_by'), table_name='discussion_threads')
    op.drop_table('discussion_threads')
    # ### end Alembic commands ###
