"""add rationale column to decisions

Revision ID: 3013a5847f8d
Revises: 85a9d7f952e2
Create Date: 2026-08-25 22:38:52.016016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3013a5847f8d'
down_revision: Union[str, Sequence[str], None] = '85a9d7f952e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decisions', sa.Column('rationale', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decisions', 'rationale')
    # ### end Alembic commands ###
