"""add activity logs

Revision ID: 4825bdeeb2e3
Revises: 2203bce1ecbd
Create Date: 2026-08-30 23:41:12.745420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4825bdeeb2e3'
down_revision: Union[str, Sequence[str], None] = '2203bce1ecbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    op.drop_constraint(op.f('decision_tags_decision_id_fkey'), 'decision_tags', type_='foreignkey')
    op.drop_constraint(op.f('decision_tags_tag_id_fkey'), 'decision_tags', type_='foreignkey')
    op.create_foreign_key(None, 'decision_tags', 'decisions', ['decision_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'decision_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.alter_column('decisions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('expert_evaluations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('expert_evaluations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('expert_evaluations_alternative_id_fkey'), 'expert_evaluations', type_='foreignkey')
    op.drop_constraint(op.f('expert_evaluations_decision_id_fkey'), 'expert_evaluations', type_='foreignkey')
    op.drop_constraint(op.f('expert_evaluations_expert_id_fkey'), 'expert_evaluations', type_='foreignkey')
    op.create_foreign_key(None, 'expert_evaluations', 'users', ['expert_id'], ['id'])
    op.create_foreign_key(None, 'expert_evaluations', 'alternatives', ['alternative_id'], ['id'])
    op.create_foreign_key(None, 'expert_evaluations', 'decisions', ['decision_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expert_evaluations', type_='foreignkey')
    op.drop_constraint(None, 'expert_evaluations', type_='foreignkey')
    op.drop_constraint(None, 'expert_evaluations', type_='foreignkey')
    op.create_foreign_key(op.f('expert_evaluations_expert_id_fkey'), 'expert_evaluations', 'users', ['expert_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('expert_evaluations_decision_id_fkey'), 'expert_evaluations', 'decisions', ['decision_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('expert_evaluations_alternative_id_fkey'), 'expert_evaluations', 'alternatives', ['alternative_id'], ['id'], ondelete='CASCADE')
    op.alter_column('expert_evaluations', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('expert_evaluations', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('decisions', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_constraint(None, 'decision_tags', type_='foreignkey')
    op.drop_constraint(None, 'decision_tags', type_='foreignkey')
    op.create_foreign_key(op.f('decision_tags_tag_id_fkey'), 'decision_tags', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key(op.f('decision_tags_decision_id_fkey'), 'decision_tags', 'decisions', ['decision_id'], ['id'])
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
