"""create decision versions table

Revision ID: 636cb0964e44
Revises: 5b5767cab327
Create Date: 2026-08-31 18:59:14.880584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '636cb0964e44'
down_revision: Union[str, Sequence[str], None] = '5b5767cab327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('problem_statement', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('decision_id', 'version_number', name='uq_decision_version')
    )
    op.create_index('ix_decision_versions_decision_id', 'decision_versions', ['decision_id'], unique=False)
    op.create_index(op.f('ix_decision_versions_id'), 'decision_versions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decision_versions_id'), table_name='decision_versions')
    op.drop_index('ix_decision_versions_decision_id', table_name='decision_versions')
    op.drop_table('decision_versions')
    # ### end Alembic commands ###
