"""create_audit_log_and_decision_versions_tables

Revision ID: 6492a6c5b989
Revises: 6a0d2fb180b3
Create Date: 2026-08-31 20:42:56.729699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6492a6c5b989'
down_revision: Union[str, Sequence[str], None] = '6a0d2fb180b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_log_id'), 'access_log', ['id'], unique=False)
    op.create_index(op.f('ix_access_log_user_id'), 'access_log', ['user_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('create', 'update', 'delete', 'status_change', 'login', 'logout', 'login_failed', 'access', 'export', 'approve', 'reject', name='auditaction', native_enum=False), nullable=False),
    sa.Column('entity_type', sa.Enum('decision', 'alternative', 'comment', 'discussion_thread', 'meeting_note', 'user', 'auth', 'system', name='auditentitytype', native_enum=False), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('old_values', sa.Text(), nullable=True),
    sa.Column('new_values', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action IN ('create','update','delete','status_change','login','logout','login_failed','access','export','approve','reject')", name='check_valid_audit_action'),
    sa.CheckConstraint("entity_type IN ('decision','alternative','comment','discussion_thread','meeting_note','user','auth','system')", name='check_valid_audit_entity_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    idx_audit_log_user_id='ix_audit_log_user_id'
    )
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('security_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Enum('login', 'logout', 'login_failed', 'password_changed', 'role_changed', 'token_refreshed', 'account_locked', 'unauthorized_access', name='securityeventtype', native_enum=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_type IN ('login','logout','login_failed','password_changed','role_changed','token_refreshed','account_locked','unauthorized_access')", name='check_valid_security_event_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_log_id'), 'security_log', ['id'], unique=False)
    op.create_index(op.f('ix_security_log_user_id'), 'security_log', ['user_id'], unique=False)
    op.create_table('decision_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('problem_statement', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('decision_id', 'version_number', name='uq_decision_version')
    )
    op.create_index(op.f('ix_decision_versions_decision_id'), 'decision_versions', ['decision_id'], unique=False)
    op.create_index(op.f('ix_decision_versions_id'), 'decision_versions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decision_versions_id'), table_name='decision_versions')
    op.drop_index(op.f('ix_decision_versions_decision_id'), table_name='decision_versions')
    op.drop_table('decision_versions')
    op.drop_index(op.f('ix_security_log_user_id'), table_name='security_log')
    op.drop_index(op.f('ix_security_log_id'), table_name='security_log')
    op.drop_table('security_log')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_access_log_user_id'), table_name='access_log')
    op.drop_index(op.f('ix_access_log_id'), table_name='access_log')
    op.drop_table('access_log')
    # ### end Alembic commands ###
