"""create decisions table

Revision ID: 6a3a79c14187
Revises: 34e0aafc2de0
Create Date: 2026-08-13 20:02:25.998275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a3a79c14187'
down_revision: Union[str, Sequence[str], None] = '34e0aafc2de0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'department',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'designation',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'designation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'department',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
