"""add user profile fields

Revision ID: 79c1e48ad7ce
Revises: 5664433f8f96
Create Date: 2026-08-11 14:02:00.819051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79c1e48ad7ce'
down_revision: Union[str, Sequence[str], None] = '5664433f8f96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Step 1: Add columns temporarily as nullable
    op.add_column(
        'users',
        sa.Column('employee_id', sa.String(), nullable=True)
    )

    op.add_column(
        'users',
        sa.Column('department', sa.String(), nullable=True)
    )

    op.add_column(
        'users',
        sa.Column('designation', sa.String(), nullable=True)
    )

    op.add_column(
        'users',
        sa.Column('phone_number', sa.String(), nullable=True)
    )

    # Step 2: Give existing users values
    op.execute("""
        UPDATE users
        SET
            employee_id = 'EMP-' || id::text,
            department = 'Not Assigned',
            designation = 'Not Assigned',
            phone_number = 'Not Provided'
        WHERE employee_id IS NULL
    """)

    # Step 3: Make the columns required
    op.alter_column(
        'users',
        'employee_id',
        existing_type=sa.String(),
        nullable=False
    )

    op.alter_column(
        'users',
        'department',
        existing_type=sa.String(),
        nullable=False
    )

    op.alter_column(
        'users',
        'designation',
        existing_type=sa.String(),
        nullable=False
    )

    op.alter_column(
        'users',
        'phone_number',
        existing_type=sa.String(),
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'designation')
    op.drop_column('users', 'department')
    op.drop_column('users', 'employee_id')
    # ### end Alembic commands ###
