"""add decision rationale

Revision ID: 7c2c93178f4c
Revises: 54721fd44eee
Create Date: 2026-08-30 11:26:18.873345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c2c93178f4c'
down_revision: Union[str, Sequence[str], None] = '54721fd44eee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decisions', sa.Column('rationale', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decisions', 'rationale')
    # ### end Alembic commands ###
