"""create meeting_notes table

Revision ID: 85a9d7f952e2
Revises: a9b7255d0c2f
Create Date: 2026-08-25 20:26:17.812476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85a9d7f952e2'
down_revision: Union[str, Sequence[str], None] = 'a9b7255d0c2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('meeting_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_notes_created_by'), 'meeting_notes', ['created_by'], unique=False)
    op.create_index(op.f('ix_meeting_notes_decision_id'), 'meeting_notes', ['decision_id'], unique=False)
    op.create_index(op.f('ix_meeting_notes_id'), 'meeting_notes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_notes_id'), table_name='meeting_notes')
    op.drop_index(op.f('ix_meeting_notes_decision_id'), table_name='meeting_notes')
    op.drop_index(op.f('ix_meeting_notes_created_by'), table_name='meeting_notes')
    op.drop_table('meeting_notes')
    # ### end Alembic commands ###
