"""add rationale to decisions

Revision ID: 97cc263c1096
Revises: 0a170e6a78d6
Create Date: 2026-08-21 10:43:09.355712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97cc263c1096'
down_revision: Union[str, Sequence[str], None] = '0a170e6a78d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decisions', sa.Column('rationale', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decisions', 'rationale')
    # ### end Alembic commands ###
