"""add tags to decisions

Revision ID: a00ca0879a09
Revises: 1c35dee4a248
Create Date: 2026-09-03 12:17:43.332522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a00ca0879a09'
down_revision: Union[str, Sequence[str], None] = '1c35dee4a248'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decisions', sa.Column('tags', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decisions', 'tags')
    # ### end Alembic commands ###
