"""create discussion_threads table

Revision ID: a9b7255d0c2f
Revises: 72f74061fb2d
Create Date: 2026-08-25 20:18:13.764478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9b7255d0c2f'
down_revision: Union[str, Sequence[str], None] = '72f74061fb2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discussion_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discussion_threads_created_by'), 'discussion_threads', ['created_by'], unique=False)
    op.create_index(op.f('ix_discussion_threads_decision_id'), 'discussion_threads', ['decision_id'], unique=False)
    op.create_index(op.f('ix_discussion_threads_id'), 'discussion_threads', ['id'], unique=False)
    op.add_column('comments', sa.Column('thread_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_comments_thread_id'), 'comments', ['thread_id'], unique=False)
    op.create_foreign_key(None, 'comments', 'discussion_threads', ['thread_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_index(op.f('ix_comments_thread_id'), table_name='comments')
    op.drop_column('comments', 'thread_id')
    op.drop_index(op.f('ix_discussion_threads_id'), table_name='discussion_threads')
    op.drop_index(op.f('ix_discussion_threads_decision_id'), table_name='discussion_threads')
    op.drop_index(op.f('ix_discussion_threads_created_by'), table_name='discussion_threads')
    op.drop_table('discussion_threads')
    # ### end Alembic commands ###
