"""add thread reference to comments

Revision ID: acb80a1e3030
Revises: 1f5060647b0f
Create Date: 2026-08-21 10:12:20.661321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acb80a1e3030'
down_revision: Union[str, Sequence[str], None] = '1f5060647b0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('thread_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'discussion_threads', ['thread_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'thread_id')
    # ### end Alembic commands ###
