"""add password column to users

Revision ID: aef8fa6c4f2f
Revises: 7d0df8f824d2
Create Date: 2026-08-10 03:49:11.057146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aef8fa6c4f2f'
down_revision: Union[str, Sequence[str], None] = '7d0df8f824d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('users', sa.Column('password', sa.String(), nullable=False, server_default=''))
    op.execute('ALTER TABLE users ALTER COLUMN password DROP DEFAULT')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
