"""create security and access logs tables

Revision ID: cb236532e217
Revises: 636cb0964e44
Create Date: 2026-09-01 19:09:40.691962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb236532e217'
down_revision: Union[str, Sequence[str], None] = '636cb0964e44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_access_logs_action', 'access_logs', ['action'], unique=False)
    op.create_index('ix_access_logs_created_at', 'access_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_access_logs_id'), 'access_logs', ['id'], unique=False)
    op.create_index('ix_access_logs_resource_id', 'access_logs', ['resource_id'], unique=False)
    op.create_index('ix_access_logs_resource_type', 'access_logs', ['resource_type'], unique=False)
    op.create_index('ix_access_logs_user_id', 'access_logs', ['user_id'], unique=False)
    op.create_table('security_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_security_logs_created_at', 'security_logs', ['created_at'], unique=False)
    op.create_index('ix_security_logs_event_type', 'security_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_security_logs_id'), 'security_logs', ['id'], unique=False)
    op.create_index('ix_security_logs_user_id', 'security_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_security_logs_user_id', table_name='security_logs')
    op.drop_index(op.f('ix_security_logs_id'), table_name='security_logs')
    op.drop_index('ix_security_logs_event_type', table_name='security_logs')
    op.drop_index('ix_security_logs_created_at', table_name='security_logs')
    op.drop_table('security_logs')
    op.drop_index('ix_access_logs_user_id', table_name='access_logs')
    op.drop_index('ix_access_logs_resource_type', table_name='access_logs')
    op.drop_index('ix_access_logs_resource_id', table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_id'), table_name='access_logs')
    op.drop_index('ix_access_logs_created_at', table_name='access_logs')
    op.drop_index('ix_access_logs_action', table_name='access_logs')
    op.drop_table('access_logs')
    # ### end Alembic commands ###
