"""add decision rationale

Revision ID: d162bedc5709
Revises: c574ac26a316
Create Date: 2026-09-01 22:15:03.636931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd162bedc5709'
down_revision: Union[str, Sequence[str], None] = 'c574ac26a316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decisions', sa.Column('rationale', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decisions', 'rationale')
    # ### end Alembic commands ###
