"""add thread id to comments

Revision ID: dd2427b8c47f
Revises: 7bcb5f1b2abb
Create Date: 2026-08-25 01:01:24.829471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd2427b8c47f'
down_revision: Union[str, Sequence[str], None] = '7bcb5f1b2abb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('thread_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'discussion_threads', ['thread_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'thread_id')
    # ### end Alembic commands ###
