import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { decisionsApi } from '../services/api';
import { ErrorState, LoadingState } from '../components/ui';
import { validateDecision } from '../services/validation';

const categories = ['Technology', 'Finance', 'Operations', 'Human Resources', 'Security', 'Product', 'Infrastructure', 'Strategy'];
const initial = { title: '', problem_statement: '', category: 'Technology', rationale: '' };
const input = 'mt-1 w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-800 outline-none focus:border-emerald-600 focus:ring-2 focus:ring-emerald-100';

export default function DecisionEditor() {
  const { id } = useParams(); const editing = Boolean(id); const navigate = useNavigate(); const [form, setForm] = useState(initial); const [loading, setLoading] = useState(editing); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [saved, setSaved] = useState('');
  useEffect(() => { if (!editing) return; decisionsApi.get(id).then((item) => setForm({ title: item.title || '', problem_statement: item.problem_statement || '', category: item.category || 'Technology', rationale: item.rationale || '' })).catch((err) => setError(err.message)).finally(() => setLoading(false)); }, [id, editing]);
  function update(event) { setForm({ ...form, [event.target.name]: event.target.value }); }
  async function submit(event) { event.preventDefault(); setError(''); setSaved(''); const validationError = validateDecision(form); if (validationError) return setError(validationError); setBusy(true); try { const payload = { title: form.title.trim(), problem_statement: form.problem_statement.trim(), category: form.category }; const result = editing ? await decisionsApi.update(id, payload) : await decisionsApi.create(payload); if (editing && form.rationale !== undefined) await decisionsApi.updateRationale(id, form.rationale); setSaved(editing ? 'Decision updated and version history recorded.' : 'Decision created successfully.'); setTimeout(() => navigate(`/decisions/${result.id}`), 500); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  if (loading) return <LoadingState label="Loading decision for editing..." />; if (error && editing && !form.title) return <ErrorState message={error} />;
  return <div><div className="mb-7"><p className="text-[11px] font-bold uppercase tracking-[.14em] text-emerald-700">{editing ? 'Edit record' : 'New record'}</p><h1 className="mt-2 font-display text-3xl font-bold tracking-tight text-slate-900">{editing ? 'Edit decision' : 'Create a decision'}</h1><p className="mt-2 text-sm text-slate-500">Capture the context your team will need when this choice comes up again.</p></div><form className="max-w-4xl rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7" onSubmit={submit}>{error && <div className="mb-5 rounded-lg border border-rose-200 bg-rose-50 px-3 py-2.5 text-sm text-rose-700">{error}</div>}{saved && <div className="mb-5 rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2.5 text-sm text-emerald-700">{saved}</div>}<div className="grid gap-5 sm:grid-cols-2"><label className="block text-sm font-semibold text-slate-600">Decision title<input className={input} maxLength="160" name="title" required value={form.title} onChange={update} placeholder="Choose a customer identity provider" /></label><label className="block text-sm font-semibold text-slate-600">Category<select className={input} name="category" required value={form.category} onChange={update}>{categories.map((value) => <option key={value}>{value}</option>)}</select></label></div><label className="mt-5 block text-sm font-semibold text-slate-600">Problem statement<textarea className={input} maxLength="4000" name="problem_statement" required value={form.problem_statement} onChange={update} rows="5" placeholder="What decision needs to be made, and why now?" /></label><label className="mt-5 block text-sm font-semibold text-slate-600">Additional rationale<textarea className={input} maxLength="4000" name="rationale" value={form.rationale} onChange={update} rows="5" placeholder="What context or constraints should future readers understand?" /></label><p className="mt-3 text-xs text-slate-400">Objectives, stakeholders, evaluation criteria, risks, tags, and alternatives are managed on the decision details page after creation.</p><div className="mt-7 flex justify-end gap-3"><button type="button" className="rounded-lg border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-700" onClick={() => navigate(editing ? `/decisions/${id}` : '/decisions')}>Cancel</button><button className="rounded-lg bg-emerald-700 px-4 py-2.5 text-sm font-semibold text-white hover:bg-emerald-800 disabled:opacity-60" disabled={busy}>{busy ? 'Saving...' : editing ? 'Save changes' : 'Create decision'}</button></div></form></div>;
}
