import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { alternativesApi, decisionsApi, discussionsApi } from '../services/api';
import { EmptyState, ErrorState, LoadingState, StatusBadge } from '../components/ui';

export default function DecisionDetail() {
  const { id } = useParams(); const [record, setRecord] = useState(null); const [alternatives, setAlternatives] = useState([]); const [comments, setComments] = useState([]); const [comment, setComment] = useState(''); const [error, setError] = useState('');
  async function load() { try { const [decision, options, discussion] = await Promise.all([decisionsApi.get(id), alternativesApi.listForDecision(id).catch(() => []), discussionsApi.getComments(id).catch(() => [])]); setRecord(decision); setAlternatives(Array.isArray(options) ? options : options.items || []); setComments(Array.isArray(discussion) ? discussion : discussion.items || []); } catch (err) { setError(err.message); } }
  useEffect(() => { load(); }, [id]);
  async function addComment(event) { event.preventDefault(); if (!comment.trim()) return; await discussionsApi.addComment(id, comment); setComment(''); load(); }
  if (error) return <ErrorState message={error} />; if (!record) return <LoadingState label="Loading decision..." />;
  return <><div className="page-header"><div className="page-header-text"><p className="eyebrow">Decision record</p><h1>{record.title}</h1><p>{record.category || 'Uncategorised'} · created {record.created_at ? new Date(record.created_at).toLocaleDateString() : 'recently'}</p></div><StatusBadge status={record.status} /></div><div className="detail-grid"><div><section className="panel detail-section"><h2>Decision information</h2><dl><dt>Problem statement</dt><dd>{record.problem_statement || 'Not provided'}</dd><dt>Objectives</dt><dd>{record.objectives || 'Not provided'}</dd><dt>Stakeholders</dt><dd>{record.stakeholders || 'Not provided'}</dd><dt>Evaluation criteria</dt><dd>{record.evaluation_criteria || 'Not provided'}</dd><dt>Risks</dt><dd>{record.risks || 'Not provided'}</dd></dl></section><section className="panel detail-section"><div className="panel-heading"><h2>Alternatives</h2><button className="btn btn-secondary btn-sm">+ Add alternative</button></div>{alternatives.length ? alternatives.map((option) => <article className="alternative-row" key={option.id}><strong>{option.name || option.title}</strong><span>{option.description || option.pros || 'No detail provided'}</span></article>) : <EmptyState title="No alternatives yet" message="Add options to make the trade-offs visible." />}</section></div><aside><section className="panel detail-section"><h2>Discussion</h2>{comments.length ? comments.map((item) => <article className="comment" key={item.id}><strong>{item.user?.full_name || item.author?.full_name || 'Team member'}</strong><small>{item.created_at ? new Date(item.created_at).toLocaleString() : ''}</small><p>{item.content}</p></article>) : <EmptyState title="Start the discussion" message="Capture questions and context alongside the decision." />}<form className="comment-form" onSubmit={addComment}><textarea value={comment} onChange={(event) => setComment(event.target.value)} placeholder="Add a comment..." rows="3" /><button className="btn btn-primary btn-block">Post comment</button></form></section><section className="panel detail-section"><h2>History</h2><p className="muted">Version and approval activity are retained by the backend audit trail.</p><Link to="/audit">View activity</Link></section></aside></div></>;
}