import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { decisionsApi } from '../services/api';

const initial = { title: '', problem_statement: '', category: '', objectives: '', stakeholders: '', evaluation_criteria: '', risks: '', rationale: '' };
export default function DecisionForm() {
  const [form, setForm] = useState(initial); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const navigate = useNavigate();
  function update(event) { setForm({ ...form, [event.target.name]: event.target.value }); }
  async function submit(event) { event.preventDefault(); setError(''); if (form.title.trim().length < 3 || form.problem_statement.trim().length < 10) return setError('Add a clear title and a problem statement of at least 10 characters.'); setBusy(true); try { const created = await decisionsApi.create(form); navigate(`/decisions/${created.id}`); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  return <><div className="page-header"><div className="page-header-text"><p className="eyebrow">New record</p><h1>Create a decision</h1><p>Give the future version of your team enough context to understand the call.</p></div></div><form className="form-panel" onSubmit={submit}>{error && <div className="alert alert-error">{error}</div>}<div className="form-grid"><label>Decision title<input name="title" required value={form.title} onChange={update} placeholder="e.g. Choose a customer identity provider" /></label><label>Category<input name="category" value={form.category} onChange={update} placeholder="Architecture, product, operations..." /></label></div><label>Problem statement<textarea name="problem_statement" required value={form.problem_statement} onChange={update} rows="4" placeholder="What decision needs to be made, and why now?" /></label><div className="form-grid"><label>Objectives<textarea name="objectives" value={form.objectives} onChange={update} rows="3" /></label><label>Stakeholders<textarea name="stakeholders" value={form.stakeholders} onChange={update} rows="3" /></label><label>Evaluation criteria<textarea name="evaluation_criteria" value={form.evaluation_criteria} onChange={update} rows="3" /></label><label>Risks<textarea name="risks" value={form.risks} onChange={update} rows="3" /></label></div><label>Additional rationale<textarea name="rationale" value={form.rationale} onChange={update} rows="4" /></label><div className="form-actions"><button type="button" className="btn btn-secondary" onClick={() => navigate('/decisions')}>Cancel</button><button className="btn btn-primary" disabled={busy}>{busy ? 'Saving...' : 'Create decision'}</button></div></form></>;
}