import { useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { decisionsApi, tagsApi } from '../services/api';
import { EmptyState, ErrorState, LoadingState, StatusBadge } from '../components/ui';

export default function Decisions() {
  const [params, setParams] = useSearchParams(); const [items, setItems] = useState(null); const [error, setError] = useState(''); const query = params.get('q') || ''; const status = params.get('status') || '';
  useEffect(() => { const load = query ? decisionsApi.search(query, { status }) : decisionsApi.list({ status }); load.then((result) => setItems(Array.isArray(result) ? result : result.items || result.results || [])).catch((err) => setError(err.message)); }, [query, status]);
  if (error) return <ErrorState message={error} />; if (!items) return <LoadingState label="Loading decisions..." />;
  return <><div className="page-header"><div className="page-header-text"><p className="eyebrow">Decision management</p><h1>Decisions</h1><p>Find, update, and move important choices through review.</p></div><Link className="btn btn-primary" to="/decisions/new">+ Create decision</Link></div><form className="filter-toolbar" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); setParams({ q: form.get('q'), status: form.get('status') }); }}><input name="q" defaultValue={query} placeholder="Search decisions..." /><select name="status" defaultValue={status}><option value="">All statuses</option><option value="draft">Draft</option><option value="under_review">Under review</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select><button className="btn btn-secondary">Filter</button></form><section className="panel">{items.length ? <div className="table-wrap"><table><thead><tr><th>Title</th><th>Category</th><th>Created by</th><th>Status</th><th>Updated</th><th /></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><strong>{item.title}</strong><small>{item.problem_statement?.slice(0, 80) || 'No problem statement'}</small></td><td>{item.category || '—'}</td><td>{item.created_by_name || item.creator?.full_name || 'You'}</td><td><StatusBadge status={item.status} /></td><td>{item.updated_at ? new Date(item.updated_at).toLocaleDateString() : '—'}</td><td><Link className="table-action" to={`/decisions/${item.id}`}>View</Link></td></tr>)}</tbody></table></div> : <EmptyState title="No decisions found" message="Try changing your filters or create a new decision." />}</section></>;
}